AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-0cde6390e61a03eee  # Update this to a valid AMI ID in your region
  MyS3Bucket:
    Type: AWS::S3::Bucket
