name: Deploy AWS Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t infra-provision .

        # Debugging Step: Print the environment variables (remove this after debugging)
    - name: Debug Environment Variables
      run: |
        echo "AWS_ACCESS_KEY_ID length: ${#AWS_ACCESS_KEY_ID}"
        echo "AWS_SECRET_ACCESS_KEY length: ${#AWS_SECRET_ACCESS_KEY}"
        echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
        echo "EC2_KEY: $EC2_KEY"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      shell: bash
