name: Deploy AWS Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t infra-provision .

    # Debugging Step: Print the environment variables (do not expose secrets in a real production environment)
    - name: Debug Environment Variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"
        echo "EC2_KEY=${{ secrets.EC2_KEY }}"
      shell: bash

    # Step 4: Run the Docker container
    - name: Run CloudFormation Automation
      run: |
        docker run --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                   --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                   --env AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
                   --env EC2_KEY=${{ secrets.EC2_KEY }} \
                   infra-provision
      shell: bash
